version: '3.5'

services:
  postgres:
    container_name: kanban-db
    build:
      context: ./compose-postgres
      dockerfile: Dockerfile.pgdb
    image: pg-kanban:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data
      POSTGRES_DB: pgkanban 
    volumes:
      - pgdata:/data
      - pglogs:/logs
      - pgprov:/docker-entrypoint-initdb.d/
    command: >
      postgres -c logging_collector=on 
      -c log_destination=stderr 
      -c log_directory=/logs 
      -c log_filename=postgresql.log 
      -c log_file_mode=0600 
      -c log_truncate_on_rotation=on 
      -c log_rotation_age=1d 
      -c log_rotation_size=10MB  
      -c shared_preload_libraries='pg_stat_statements'
    ports:
      - "5432:5432"
    networks:
      kblnet:
        ipv4_address: 70.10.3.10
    restart: unless-stopped

  web:
    container_name: kanban-web
    build:
      context: ./server/app
    image: kanban-web:latest
    depends_on: 
      - postgres
    ports:
      - "${NODEPORT:-4001}:4001"
    environment:
      DB_HOST: '70.10.3.10'
      DB_USER: ${POSTGRES_USER:-postgres} 
      DB_PASS: ${POSTGRES_PASSWORD:-changeme}
      DB_NAME: ${POSTGRES_DB:-pgkanban}
    networks:
      kblnet:
        ipv4_address: 70.10.3.30
    restart: unless-stopped

  pgadmin:
    container_name: kanban-db-admin
    build:
      context: ./compose-postgres
      dockerfile: Dockerfile.pgadmin
    image: kanban-db-admin:latest
    depends_on: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: ${PGADMIN_SERVER_JSON_FILE:-/pgadmin4/pgadminServers.json}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      kblnet:
        ipv4_address: 70.10.3.20
    restart: unless-stopped

networks:
  kblnet:
    external: true    

volumes:
  pgdata:
  pglogs:
  pgprov:
  pgadmin: