version: '3.5'

services:
  postgres:
    container_name: kanban-db
    image: pg-kanban:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data
      POSTGRES_DB: pgkanban 
    volumes:
      - pgdata:/data
      - pglogs:/logs
      - type: bind
        source: ./compose-postgres/provision
        target: /docker-entrypoint-initdb.d/ 
    command: >
      postgres -c logging_collector=on 
      -c log_destination=stderr 
      -c log_directory=/logs 
      -c log_filename=postgresql.log 
      -c log_file_mode=0600 
      -c log_truncate_on_rotation=on 
      -c log_rotation_age=1d 
      -c log_rotation_size=10MB  
      -c shared_preload_libraries='pg_stat_statements'
    ports:
      - "5432:5432"
    networks:
      kblnet:
        ipv4_address: 70.10.3.10
    restart: unless-stopped

  web:
    container_name: kanban-web
    image: kanban-web:latest
    command: npm start
    depends_on: 
      - postgres
    ports:
      - "${NODEPORT:-4001}:4001"
    environment:
      DB_HOST: '70.10.3.10'
      DB_USER: 'postgres' 
      DB_PASS: 'changeme'
      DB_NAME: 'pgkanban'
    networks:
      kblnet:
        ipv4_address: 70.10.3.30
    restart: unless-stopped

  pgadmin:
    container_name: kanban-db-admin
    image: pgadmin:latest
    depends_on: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-harvash2004@yahoo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      kblnet:
        ipv4_address: 70.10.3.20
    restart: unless-stopped

networks:
  kblnet:
    external: true    

volumes:
  pgdata:
  pglogs:
  pgadmin: