apiVersion: v1
kind: Service
metadata: 
  name: postgres
  labels:
    db: postgres
spec:
  selector:
    db: postgres
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  selector: 
    matchLabels:
      db: postgres
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        db: postgres
        tier: backend
    spec:
      containers:
      - name: kanban-pg
        image: fskubecr.azurecr.io/kanban-pg
        imagePullPolicy: Always
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: pgdata
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: changeme
        - name: POSTGRES_DB
          value: pgkanban 
        - name: PGDATA 
          value: /data/pgdata
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 999:999 /data"]
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi