apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
    tier: frontend
  ports:
  - port: 5051
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      tier: frontend
  template:
    metadata:
      labels:
        app: pgadmin
        tier: frontend
    spec:
      containers:
      - name: kanban-db-admin
        image: fskubecr.azurecr.io/kanban-db-admin:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5050
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin