- name: Deploy the Kanban Life Application
  hosts: localhost
  connection: local
  vars_files:
    - vars/kanban-vars.yaml
  vars:
    resource_group: FSKubeRG
    location: eastus
    aks_name: FSKubeCluster
    aks_version: aks_version
  tasks:
    - name: create kanban namespace
      k8s:
        kind: namespace
        api_version: v1
        name: kanban
        state: present

    - name: deploy kanban-pg
      k8s:
        namespace: kanban
        apply: yes
        definition: "{{ lookup('file', '../../k8s/deploy_backend.yaml') }}"

    - name: deploy kanban-db-admin
      k8s:
        namespace: kanban
        apply: yes
        definition: "{{ lookup('file', '../../k8s/deploy_frontend.yaml') }}"

    - name: deploy kanban-app
      k8s:
        namespace: kanban
        apply: yes
        definition: "{{ lookup('file', '../../k8s/deploy_web.yaml') }}"